export interface ContractData {
  contractNumber:  string;
  date:            string;
  client:    { name: string; email: string; company?: string };
  consultant:{ name: string; email: string; title?: string  };
  projectTitle:    string;
  projectScope:    string;
  deliverables:    string[];
  startDate:       string;
  endDate?:        string;
  totalAmount:     number;
  paymentTerms:    string;
  currency?:       string;
  governingLaw?:   string;
}

export function buildContractHtml(d: ContractData): string {
  const cur  = d.currency ?? "$";
  const date = new Date().toLocaleDateString("en-GB", { day: "2-digit", month: "long", year: "numeric" });

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Service Agreement — ${d.contractNumber}</title>
<style>
  body { font-family: "Georgia", serif; margin: 0; padding: 48px; color: #111; line-height: 1.7; max-width: 800px; margin: auto; }
  h1   { font-size: 22px; text-align: center; text-transform: uppercase; letter-spacing: 0.12em; margin-bottom: 4px; }
  .sub { text-align: center; color: #666; font-size: 13px; margin-bottom: 40px; }
  h2   { font-size: 14px; text-transform: uppercase; letter-spacing: 0.08em; margin-top: 32px; border-bottom: 1px solid #ddd; padding-bottom: 6px; }
  .parties-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 32px; margin: 24px 0; }
  .party-box { border: 1px solid #ddd; padding: 16px; border-radius: 6px; }
  .party-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; color: #999; margin-bottom: 6px; }
  ul { padding-left: 20px; }
  li { margin-bottom: 4px; }
  .sig-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 48px; margin-top: 60px; }
  .sig-line { border-top: 1px solid #333; padding-top: 8px; font-size: 13px; color: #555; }
  .footer { margin-top: 48px; text-align: center; font-size: 11px; color: #bbb; }
  .highlight { color: #2563EB; font-weight: bold; }
</style>
</head>
<body>
  <h1>Consulting Services Agreement</h1>
  <div class="sub">Contract #${d.contractNumber} · Issued ${date}</div>

  <h2>1. Parties</h2>
  <div class="parties-grid">
    <div class="party-box">
      <div class="party-label">Client</div>
      <strong>${d.client.name}</strong><br/>
      ${d.client.company ? `${d.client.company}<br/>` : ""}
      ${d.client.email}
    </div>
    <div class="party-box">
      <div class="party-label">Consultant</div>
      <strong>${d.consultant.name}</strong><br/>
      ${d.consultant.title ? `${d.consultant.title}<br/>` : ""}
      ${d.consultant.email}
    </div>
  </div>

  <h2>2. Project</h2>
  <p><strong>Title:</strong> ${d.projectTitle}</p>
  <p><strong>Scope:</strong> ${d.projectScope}</p>

  <h2>3. Deliverables</h2>
  <ul>${d.deliverables.map(del => `<li>${del}</li>`).join("")}</ul>

  <h2>4. Timeline</h2>
  <p><strong>Start Date:</strong> ${d.startDate}</p>
  ${d.endDate ? `<p><strong>End Date:</strong> ${d.endDate}</p>` : ""}

  <h2>5. Fees &amp; Payment</h2>
  <p><strong>Total Amount:</strong> <span class="highlight">${cur}${d.totalAmount.toLocaleString()}</span></p>
  <p><strong>Payment Terms:</strong> ${d.paymentTerms}</p>
  <p>All payments are processed via Lamid's milestone escrow system. Funds are held in escrow and released upon client approval of each deliverable.</p>

  <h2>6. Intellectual Property</h2>
  <p>Upon full payment, the Client shall own all work product produced under this Agreement. The Consultant retains the right to reference this engagement in their portfolio.</p>

  <h2>7. Confidentiality</h2>
  <p>Both parties agree to keep all non-public information exchanged during this engagement strictly confidential for a period of two (2) years.</p>

  <h2>8. Termination</h2>
  <p>Either party may terminate this Agreement with 14 days' written notice. Fees for completed work are non-refundable.</p>

  <h2>9. Governing Law</h2>
  <p>This Agreement is governed by the laws of ${d.governingLaw ?? "<strong>[GOVERNING LAW — TO BE COMPLETED BY THE PARTIES]</strong>"}.</p>

  <h2>10. Signatures</h2>
  <div class="sig-grid">
    <div>
      <div style="height:60px;"></div>
      <div class="sig-line">${d.client.name}<br/><em>Client</em> · ${date}</div>
    </div>
    <div>
      <div style="height:60px;"></div>
      <div class="sig-line">${d.consultant.name}<br/><em>Consultant</em> · ${date}</div>
    </div>
  </div>

  <div class="footer">Generated by LAMID ONE · lamid.io</div>
</body>
</html>`;
}
