export interface InvoiceData {
  invoiceNumber: string;
  date:          string;
  dueDate?:      string;
  from: { name: string; email: string; address?: string };
  to:   { name: string; email: string; address?: string };
  items: { description: string; quantity: number; unitPrice: number }[];
  notes?: string;
  currency?: string;
}

export function buildInvoiceHtml(data: InvoiceData): string {
  const cur     = data.currency ?? "$";
  const subtotal = data.items.reduce((s, i) => s + i.quantity * i.unitPrice, 0);
  const tax      = 0; // Add tax logic when needed
  const total    = subtotal + tax;

  const rows = data.items.map(item => `
    <tr>
      <td style="padding:10px 0;border-bottom:1px solid #f0f0f0;">${item.description}</td>
      <td style="padding:10px 0;border-bottom:1px solid #f0f0f0;text-align:center;">${item.quantity}</td>
      <td style="padding:10px 0;border-bottom:1px solid #f0f0f0;text-align:right;">${cur}${item.unitPrice.toLocaleString()}</td>
      <td style="padding:10px 0;border-bottom:1px solid #f0f0f0;text-align:right;font-weight:600;">${cur}${(item.quantity * item.unitPrice).toLocaleString()}</td>
    </tr>`).join("");

  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Invoice ${data.invoiceNumber}</title>
<style>
  body { font-family: Arial, sans-serif; margin: 0; padding: 40px; color: #333; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 40px; }
  .brand  { font-size: 24px; font-weight: 900; color: #2563EB; }
  .invoice-meta { text-align: right; }
  .invoice-meta h1 { font-size: 32px; color: #111; margin: 0 0 4px; }
  .invoice-meta p  { margin: 2px 0; color: #666; font-size: 13px; }
  .parties { display: grid; grid-template-columns: 1fr 1fr; gap: 40px; margin-bottom: 40px; }
  .party-label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.1em; color: #999; margin-bottom: 8px; }
  .party-name  { font-size: 16px; font-weight: 700; }
  .party-detail{ font-size: 13px; color: #666; }
  table { width: 100%; border-collapse: collapse; }
  th    { font-size: 11px; text-transform: uppercase; letter-spacing: 0.07em; color: #999; padding: 8px 0; border-bottom: 2px solid #eee; }
  th:last-child, td:last-child { text-align: right; }
  th:nth-child(2), td:nth-child(2) { text-align: center; }
  .totals { margin-top: 20px; text-align: right; }
  .total-row { display: flex; justify-content: flex-end; gap: 40px; padding: 6px 0; font-size: 14px; }
  .grand-total { font-size: 20px; font-weight: 900; color: #2563EB; border-top: 2px solid #111; padding-top: 8px; margin-top: 4px; }
  .notes { margin-top: 40px; padding: 16px; background: #fafafa; border-radius: 8px; font-size: 13px; color: #666; }
  .footer{ margin-top: 40px; text-align: center; font-size: 11px; color: #bbb; }
</style>
</head>
<body>
  <div class="header">
    <div class="brand">Lamid</div>
    <div class="invoice-meta">
      <h1>INVOICE</h1>
      <p><strong>#${data.invoiceNumber}</strong></p>
      <p>Date: ${data.date}</p>
      ${data.dueDate ? `<p>Due: ${data.dueDate}</p>` : ""}
    </div>
  </div>

  <div class="parties">
    <div>
      <div class="party-label">From</div>
      <div class="party-name">${data.from.name}</div>
      <div class="party-detail">${data.from.email}</div>
      ${data.from.address ? `<div class="party-detail">${data.from.address}</div>` : ""}
    </div>
    <div>
      <div class="party-label">To</div>
      <div class="party-name">${data.to.name}</div>
      <div class="party-detail">${data.to.email}</div>
      ${data.to.address ? `<div class="party-detail">${data.to.address}</div>` : ""}
    </div>
  </div>

  <table>
    <thead><tr>
      <th style="text-align:left">Description</th>
      <th>Qty</th>
      <th style="text-align:right">Unit Price</th>
      <th style="text-align:right">Total</th>
    </tr></thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="totals">
    <div class="total-row"><span>Subtotal</span><span>${cur}${subtotal.toLocaleString()}</span></div>
    <div class="total-row grand-total"><span>Total</span><span>${cur}${total.toLocaleString()}</span></div>
  </div>

  ${data.notes ? `<div class="notes"><strong>Notes:</strong> ${data.notes}</div>` : ""}
  <div class="footer">Generated by LAMID ONE · lamid.io</div>
</body>
</html>`;
}
